services:
  mongo:
    image: mongo:6.0
    container_name: mongo_university
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - university_net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  data-generator:
    build:
      context: ./datagen
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - university_net

volumes:
  mongo_data:

networks:
  university_net:
    driver: bridge
